---
- hosts: all
  become: yes
  roles:
    - role: opendaylight
      # Install the latest ODL Carbon RPM from the CBS repos
      rpm_repo_file: "opendaylight-6-testing.repo"
      rpm_repo_url: "https://git.opendaylight.org/gerrit/gitweb?p=integration/packaging.git;a=blob_plain;f=rpm/example_repo_configs/opendaylight-6-testing.repo"
